
#Drop Rate
[DropRate]
	#Enable charged creeper explosion to drop a Axolotl head
	axolotlEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Bat head
	batEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Bee head
	beeEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Blaze head
	blazeEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Cat head
	catEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Cave Spider head
	caveSpiderEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Chicken head
	chickenEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Cow head
	cowEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Donkey head
	donkeyEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Enderman head
	endermanEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Endermite head
	endermiteEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Fox head
	foxEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Ghast head
	ghastEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Glow Squid head
	glowSquidEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Goat head
	goatEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Horse head
	horseEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Skeleton Horse head
	horseSkeletonEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Zombie Horse head
	horseUndeadEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Iron Golem head
	ironGolemEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Magma Cube head
	magmaCubeEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Mooshroom head
	mooshroomEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Ocelot head
	ocelotEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Pig head
	pigEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Piglin head
	piglinEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Piglin Brute head
	piglinBruteEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Sheep head
	sheepEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Silverfish head
	silverfishEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Slime head
	slimeEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Snow Golem head
	snowGolemEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Spider head
	spiderEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Squid head
	squidEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Turtle head
	turtleEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Villager head
	villagerEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Wandering Trader head
	wanderingTraderEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Witch head
	witchEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Wolf head
	wolfEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Zombie Villager head
	zombieVillagerEnableCreeperDrop = true
	#Enable charged creeper explosion to drop a Zombified Piglin head
	zombifiedPiglinEnableCreeperDrop = true
	#Defines the drop rate for the Axolotl heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	axolotlDropRate = 0.025
	#Defines the drop rate for the Bat head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	batDropRate = 0.025
	#Defines the drop rate for the Bee head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	beeDropRate = 0.025
	#Defines the drop rate for the Blaze head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	blazeDropRate = 0.025
	#Defines the drop rate for the Cat heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	catDropRate = 0.025
	#Defines the drop rate for the Cave Spider head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	caveSpiderDropRate = 0.025
	#Defines the drop rate for the Chicken head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	chickenDropRate = 0.025
	#Defines the drop rate for the Cow head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	cowDropRate = 0.025
	#Defines the drop rate for the Donkey head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	donkeyDropRate = 0.025
	#Defines the drop rate for the Enderman head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	endermanDropRate = 0.025
	#Defines the drop rate for the Endermite head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	endermiteDropRate = 0.025
	#Defines the drop rate for the Fox heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	foxDropRate = 0.025
	#Defines the drop rate for the Ghast head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	ghastDropRate = 0.025
	#Defines the drop rate for the Glow Squid head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	glowSquidDropRate = 0.025
	#Defines the drop rate for the Goat head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	goatDropRate = 0.025
	#Defines the drop rate for the Horse heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	horseDropRate = 0.025
	#Defines the drop rate for the Skeleton Horse head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	horseSkeletonDropRate = 0.025
	#Defines the drop rate for the Zombie Horse head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	horseUndeadDropRate = 0.025
	#Defines the drop rate for the Iron Golem head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	ironGolemDropRate = 0.025
	#Defines the drop rate for the Magma Cube head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	magmaCubeDropRate = 0.025
	#Defines the drop rate for the Mooshroom heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	mooshroomDropRate = 0.025
	#Defines the drop rate for the Ocelot head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	ocelotDropRate = 0.025
	#Defines the drop rate for the Pig head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	pigDropRate = 0.025
	#Defines the drop rate for the Piglin head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	piglinDropRate = 0.025
	#Defines the drop rate for the Piglin Brute head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	piglinBruteDropRate = 0.025
	#Defines the drop rate for the Sheep heads (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	sheepDropRate = 0.025
	#Defines the drop rate for the Silverfish head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	silverfishDropRate = 0.025
	#Defines the drop rate for the Slime head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	slimeDropRate = 0.025
	#Defines the drop rate for the Snow Golem head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	snowGolemDropRate = 0.025
	#Defines the drop rate for the Spider head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	spiderDropRate = 0.025
	#Defines the drop rate for the Squid head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	squidDropRate = 0.025
	#Defines the drop rate for the Turtle head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	turtleDropRate = 0.025
	#Defines the drop rate for the Villager head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	villagerDropRate = 0.025
	#Defines the drop rate for the Wandering Trader head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	wanderingTraderDropRate = 0.025
	#Defines the drop rate for the Witch head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	witchDropRate = 0.025
	#Defines the drop rate for the Wolf head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	wolfDropRate = 0.025
	#Defines the drop rate for the Zombie Villager head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	zombieVillagerDropRate = 0.025
	#Defines the drop rate for the Zombified Piglin head (0 to disable) [Default: 0.025]
	#Range: 0.0 ~ 1.0
	zombifiedPiglinDropRate = 0.025

