
#General settings
[General]
	#Dictates the 1 in X chance the Oreberry Bush grows every time it tries to grow [Default: 20]
	#Range: > 1
	growthChance = 20

#Generation settings
[Generation]
	#Generate Iron Bushes [Default: true]
	generateIronBush = false
	#Generate Gold Bushes [Default: true]
	generateGoldBush = false
	#Generate Copper Bushes [Default: true]
	generateCopperBush = false
	#Generate Tin Bushes [Default: false]
	generateTinBush = false
	#Generate Aluminum Bushes [Default: false]
	generateAluminumBush = false
	#Generate Lead Bushes [Default: false]
	generateLeadBush = false
	#Generate Nickel Bushes [Default: false]
	generateNickelBush = false
	#Generate Uranium Bushes [Default: false]
	generateUraniumBush = false
	#Generate Osmium Bushes [Default: false]
	generateOsmiumBush = false
	#Generate Zinc Bushes [Default: false]
	generateZincBush = false
	#Generate Silver Bushes [Default: false]
	generateSilverBush = false
	#Generate Essence Bushes [Default: true]
	generateEssenceBush = true

#Placement settings
[Placement]
	#Only allow placing Iron Bushes in darkness [Default: true]
	darknessOnlyIronBush = true
	#Only allow placing Gold Bushes in darkness [Default: true]
	darknessOnlyGoldBush = true
	#Only allow placing Copper Bushes in darkness [Default: true]
	darknessOnlyCopperBush = true
	#Only allow placing Tin Bushes in darkness [Default: true]
	darknessOnlyTinBush = true
	#Only allow placing Aluminum Bushes in darkness [Default: true]
	darknessOnlyAluminumBush = true
	#Only allow placing Lead Bushes in darkness [Default: true]
	darknessOnlyLeadBush = true
	#Only allow placing Nickel Bushes in darkness [Default: true]
	darknessOnlyNickelBush = true
	#Only allow placing Uranium Bushes in darkness [Default: true]
	darknessOnlyUraniumBush = true
	#Only allow placing Osmium Bushes in darkness [Default: true]
	darknessOnlyOsmiumBush = true
	#Only allow placing Zinc Bushes in darkness [Default: true]
	darknessOnlyZincBush = true
	#Only allow placing Silver Bushes in darkness [Default: true]
	darknessOnlySilverBush = true
	#Only allow placing Essence Bushes in darkness [Default: true]
	darknessOnlyEssenceBush = false

#Density settings
[Density]
	#Iron Bush Density [Default: 1]
	#Range: 1 ~ 32
	ironBushDensity = 1
	#Gold Bush Density [Default: 1]
	#Range: 1 ~ 32
	goldBushDensity = 1
	#Copper Bush Density [Default: 2]
	#Range: 1 ~ 32
	copperBushDensity = 1
	#Tin Bush Density [Default: 2]
	#Range: 1 ~ 32
	tinBushDensity = 1
	#Aluminum Bush Density [Default: 2]
	#Range: 1 ~ 32
	aluminumBushDensity = 1
	#Lead Bush Density [Default: 1]
	#Range: 1 ~ 32
	leadBushDensity = 1
	#Nickel Bush Density [Default: 1]
	#Range: 1 ~ 32
	nickelBushDensity = 1
	#Uranium Bush Density [Default: 1]
	#Range: 1 ~ 32
	uraniumBushDensity = 1
	#Osmium Bush Density [Default: 1]
	#Range: 1 ~ 32
	osmiumBushDensity = 1
	#Zinc Bush Density [Default: 2]
	#Range: 1 ~ 32
	zincBushDensity = 1
	#Silver Bush Density [Default: 1]
	#Range: 1 ~ 32
	silverBushDensity = 1
	#Essence Bush Density [Default: 2]
	#Range: 1 ~ 32
	essenceBushDensity = 2

#Rarity settings
[Rarity]
	#Iron Bush Rarity [Default: 5]
	#Range: > 1
	ironBushRarity = 5
	#Gold Bush Rarity [Default: 8]
	#Range: > 1
	goldBushRarity = 8
	#Copper Bush Rarity [Default: 3]
	#Range: > 1
	copperBushRarity = 3
	#Tin Bush Rarity [Default: 3]
	#Range: > 1
	tinBushRarity = 3
	#Aluminum Bush Rarity [Default: 2]
	#Range: > 1
	aluminumBushRarity = 2
	#Lead Bush Rarity [Default: 7]
	#Range: > 1
	leadBushRarity = 7
	#Nickel Bush Rarity [Default: 5]
	#Range: > 1
	nickelBushRarity = 5
	#Uranium Bush Rarity [Default: 9]
	#Range: > 1
	uraniumBushRarity = 5
	#Osmium Bush Rarity [Default: 6]
	#Range: > 1
	osmiumBushRarity = 6
	#Zinc Bush Rarity [Default: 6]
	#Range: > 1
	zincBushDensity = 6
	#Silver Bush Rarity [Default: 7]
	#Range: > 1
	silverBushRarity = 7
	#Essence Bush Rarity [Default: 6]
	#Range: > 1
	essenceBushRarity = 6

#Location settings
[Location]
	#Iron Bush Min Y [Default: -64]
	#Range: > -2147483648
	ironBushMinY = -64
	#Iron Bush Max Y [Default: 62]
	#Range: > -2147483648
	ironBushMaxY = -63
	#Gold Bush Min Y [Default: -64]
	#Range: > -2147483648
	goldBushMinY = -64
	#Gold Bush Max Y [Default: 32]
	#Range: > -2147483648
	goldBushMaxY = -63
	#Copper Bush Min Y [Default: -44]
	#Range: > -2147483648
	copperBushMinY = -44
	#Copper Bush Max Y [Default: 60]
	#Range: > -2147483648
	copperBushMaxY = -45
	#Tin Bush Min Y [Default: -44]
	#Range: > -2147483648
	tinBushMinY = -44
	#Tin Bush Max Y [Default: 60]
	#Range: > -2147483648
	tinBushMaxY = -45
	#Aluminum Bush Min Y [Default: -44]
	#Range: > -2147483648
	aluminumBushMinY = -44
	#Aluminum Bush Max Y [Default: 60]
	#Range: > -2147483648
	aluminumBushMaxY = -45
	#Lead Bush Min Y [Default: -64]
	#Range: > -2147483648
	leadBushMinY = -64
	#Lead Bush Max Y [Default: 40]
	#Range: > -2147483648
	leadBushMaxY = -63
	#Nickel Bush Min Y [Default: -64]
	#Range: > -2147483648
	nickelBushMinY = -64
	#Nickel Bush Max Y [Default: 120]
	#Range: > -2147483648
	nickelBushMaxY = -63
	#Uranium Bush Min Y [Default: -64]
	#Range: > -2147483648
	uraniumBushMinY = -64
	#Uranium Bush Max Y [Default: 60]
	#Range: > -2147483648
	uraniumBushMaxY = -63
	#Osmium Bush Min Y [Default: -64]
	#Range: > -2147483648
	osmiumBushMinY = -64
	#Osmium Bush Max Y [Default: 60]
	#Range: > -2147483648
	osmiumBushMaxY = -63
	#Zinc Bush Min Y [Default: -64]
	#Range: > -2147483648
	zincBushMinY = -64
	#Zinc Bush Max Y [Default: 70]
	#Range: > -2147483648
	zincBushMaxY = -63
	#Silver Bush Min Y [Default: -64]
	#Range: > -2147483648
	silverBushMinY = -64
	#Silver Bush Max Y [Default: 40]
	#Range: > -2147483648
	silverBushMaxY = -63
	#Essence Bush Min Y [Default: -64]
	#Range: > -2147483648
	essenceBushMinY = -64
	#Essence Bush Max Y [Default: 32]
	#Range: > -2147483648
	essenceBushMaxY = 32

